HACK: TO REMOVE: rpmsg: build only if TI tiler is present
Eventually the rpmsg will use ION, till then, it
depends on TI_TILER being configured in the system.

This fixes the build error:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
drivers/built-in.o: In function `_rpmsg_omx_map_buf':
drivers/rpmsg/rpmsg_omx.c:108: undefined reference to `tiler_virt2phys'
drivers/rpmsg/rpmsg_omx.c:117: undefined reference to `tiler_virt2phys'
make: *** [.tmp_vmlinux1] Error 1

Signed-off-by: Nishanth Menon <nm@ti.com>